version: '3.8'
services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - mynetwork

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volume:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - mynetwork

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volume:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - mynetwork